package main

// quark.go —— DR4：夸克网盘真实 remote 接入（扫码登录）。
//
// fork（v1.70.0-quark）的登录机制（二进制取证）：
//   - 认证凭据 = cookie（"generated by QR login"），存在 rclone.conf
//   - `rclone config reconnect <remote>` 触发终端 QR 流程：
//     "Scan this QR code with the Quark app, then confirm."
//     QR URL: https://su.quark.cn/4_eMHBJ?token=...
//   - cookie 空/过期时 backend 报错指引重扫；
//     已登录再走流程会问 "A Quark Drive login already exists. Log in again?"
//   - 运行期 cookie 滚动刷新（60s 节流写回 rclone.conf）
//
// 用法：
//   spike quark-login            交互式扫码（需在真实控制台跑，stdim 直通）
//   spike run -remote quark:     用真实夸克 remote 同步（默认仍是本地替身）

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// cmdQuarkLogin 配置/重新登录夸克 remote（终端扫码）。
//
// 二进制取证结论：quark backend 带交互式 Config 状态机——
// `rclone config create quark quark` 即触发 QR 流程（等 stdin）；
// cookie 空时 backend 报错指引 `rclone config reconnect`。
// 本命令必须在**真实控制台**运行（stdin/stdout 直通，QR 渲染在终端）。
func cmdQuarkLogin(args []string) {
	fs := flag.NewFlagSet("quark-login", flag.ExitOnError)
	rcloneExe := fs.String("rclone", `D:\Software\rclone\rclone.exe`, "rclone 可执行文件")
	name := fs.String("name", "quark", "remote 名称")
	_ = fs.Parse(args)

	// 1) 存在性判断：listremotes 输出 remote 名列表（config show 对不存在的
	// remote 也会输出 "[name]" 头，不可靠）
	remotes, _ := rcloneOutput(*rcloneExe, "listremotes")
	exists := false
	for _, line := range strings.Split(remotes, "\n") {
		if strings.TrimSuffix(strings.TrimSpace(line), ":") == *name {
			exists = true
			break
		}
	}

	// 2) 驱动 QR 状态机（交互直通，必须真 TTY——survey 终端 UI 在管道下静默挂起）
	fmt.Println("── 夸克扫码登录（DR4）──")
	if !exists {
		fmt.Printf("remote [%s] 不存在 → config create（终端将显示二维码）\n", *name)
	} else {
		// quark 非 OAuth backend，`config reconnect` 不支持（实测
		// "backend doesn't support reconnect"）；重扫码 = 删重建
		fmt.Printf("remote [%s] 已存在 → 删除后重建（重新扫码）\n", *name)
		_ = runRclone(*rcloneExe, "config", "delete", *name)
	}
	fmt.Println("用夸克 APP 扫描终端里的二维码并在手机上确认，等待 cookie 写入……")
	if err := runRcloneInteractive(*rcloneExe, "config", "create", *name, "quark"); err != nil {
		fmt.Printf("❌ config create 失败: %v\n", err)
		os.Exit(1)
	}

	// 3) 验证：列举 quark 根目录
	fmt.Println("── 验证连接 ──")
	if err := runRclone(*rcloneExe, "lsd", *name+":"); err != nil {
		fmt.Printf("❌ 验证失败（cookie 可能未生效）: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✅ 夸克登录完成，可运行: spike run -remote %s:\n", *name)
}

// runRclone 非交互执行 rclone 子命令（输出直通）。
func runRclone(exe string, sub ...string) error {
	c := exec.Command(exe, sub...)
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	return c.Run()
}

// runRcloneInteractive 交互执行（stdin 直通；QR/问答需要真 TTY，
// 必须在真实控制台运行本命令）。
func runRcloneInteractive(exe string, sub ...string) error {
	c := exec.Command(exe, sub...)
	c.Stdin = os.Stdin
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	return c.Run()
}

// rcloneOutput 非交互执行并捕获 stdout。
func rcloneOutput(exe string, sub ...string) (string, error) {
	c := exec.Command(exe, sub...)
	out, err := c.Output()
	return string(out), err
}

// quarkRemoteFlag 返回 run 命令使用的云端 fs。
// remote 为空 → 本地替身目录（P0/P1 测试路径）；否则为 rclone remote（如 quark:）。
func quarkRemoteFlag(remote string) string {
	return strings.TrimPrefix(remote, "/")
}
