package main

// quark.go —— DR4：夸克网盘真实 remote 接入（扫码登录）。
//
// fork（v1.70.0-quark）的登录机制（二进制取证 + --non-interactive 实测）：
//   - 认证凭据 = cookie（"generated by QR login"），存在 rclone.conf
//   - 状态机：qr_start（创建扫码会话，写 config_qr_session）→ qr_poll（等扫码确认）
//   - TTY 下 `rclone config create <name> quark` 实测**不打印任何东西**（二维码丢失），
//     但 `--non-interactive` 会把问题以 JSON 输出，其中 Option.Help 内含：
//       "Scan this QR code with the Quark app, then confirm." + ANSI 二维码
//       + "If the code does not render, open: https://su.quark.cn/4_eMHBJ?token=..."
//   - 用 --continue --state qr_poll --result true 回答后，rclone 轮询夸克直到
//     扫码确认并写 cookie（约 3 分钟未扫码则 "quark drive QR login timed out"）
//   - cookie 空/过期时 backend 报错指引重扫码
//   - 运行期 cookie 滚动刷新（60s 节流写回 rclone.conf）
//
// 用法：
//   spike quark-login             扫码登录（spike 自己渲染二维码，管道/TTY 均可）
//   spike quark-login -interactive  交给 rclone 终端渲染（需真 TTY，fork 下无输出）
//   spike run -remote quark:      用真实夸克 remote 同步（默认仍是本地替身）

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

// qrQuestion 是 rclone `config create --non-interactive` 吐出的问题 JSON。
type qrQuestion struct {
	State  string `json:"State"`
	Error  string `json:"Error"`
	Result string `json:"Result"`
	Option struct {
		Name string `json:"Name"`
		Help string `json:"Help"`
	} `json:"Option"`
}

// qrURLRe 从 Help 里抠出备用登录链接。
var qrURLRe = regexp.MustCompile(`https://\S+`)

// cmdQuarkLogin 配置/重新登录夸克 remote（扫码）。
//
// quark backend 的 Config 状态机：qr_start 建扫码会话 → qr_poll 等确认。
// 这个 fork 在 TTY 下不渲染二维码（实测零输出），所以默认走
// --non-interactive 协议：拿 JSON 里的 Option.Help（含 ANSI 二维码）由
// spike 自己打印，再 --continue 回答 qr_poll，让 rclone 轮询到扫码完成。
func cmdQuarkLogin(args []string) {
	fs := flag.NewFlagSet("quark-login", flag.ExitOnError)
	rcloneExe := fs.String("rclone", "", "rclone 可执行文件（默认：配置 > exe 同目录 > PATH）")
	name := fs.String("name", "quark", "remote 名称")
	interactive := fs.Bool("interactive", false, "交给 rclone 终端渲染二维码（fork 下实测无输出）")
	tries := fs.Int("tries", 5, "二维码超时后的自动重出次数（每次约 3 分钟）")
	_ = fs.Parse(args)
	// 优先级：flag > onerclone.json > 自动发现（纯配置命令：只读不写模板）
	*rcloneExe = resolveRclone(*rcloneExe, loadConfigOpt(false).Rclone)

	// 1) 存在性判断：listremotes 输出 remote 名列表（config show 对不存在的
	// remote 也会输出 "[name]" 头，不可靠）
	remotes, _ := rcloneOutput(*rcloneExe, "listremotes")
	exists := false
	for _, line := range strings.Split(remotes, "\n") {
		if strings.TrimSuffix(strings.TrimSpace(line), ":") == *name {
			exists = true
			break
		}
	}

	// 2) 驱动 QR 状态机
	fmt.Println("── 夸克扫码登录（DR4）──")
	if !exists {
		fmt.Printf("remote [%s] 不存在 → config create\n", *name)
	} else {
		// quark 非 OAuth backend，`config reconnect` 不支持（实测
		// "backend doesn't support reconnect"）；重扫码 = 删重建
		fmt.Printf("remote [%s] 已存在 → 删除后重建（重新扫码）\n", *name)
		_ = runRclone(*rcloneExe, "config", "delete", *name)
	}

	if *interactive {
		fmt.Println("用夸克 APP 扫描终端里的二维码并在手机上确认，等待 cookie 写入……")
		if err := runRcloneInteractive(*rcloneExe, "config", "create", *name, "quark"); err != nil {
			fmt.Printf("❌ config create 失败: %v\n", err)
			os.Exit(1)
		}
	} else {
		quarkQRLogin(*rcloneExe, *name, *tries)
	}

	// 3) 验证：列举 quark 根目录
	fmt.Println("── 验证连接 ──")
	if err := runRclone(*rcloneExe, "lsd", *name+":"); err != nil {
		fmt.Printf("❌ 验证失败（cookie 可能未生效）: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✅ 夸克登录完成，可运行: spike run -remote %s:\n", *name)
}

// quarkQRLogin 走 --non-interactive 协议完成扫码登录。
// 每次会话 rclone 只等约 3 分钟（quark drive QR login timed out），
// 超时就自动重开一轮新会话、重出二维码，直到成功或用完 tries。
func quarkQRLogin(exe, name string, tries int) {
	if tries < 1 {
		tries = 1
	}
	// Option.Help = 提示语 + ANSI 二维码 + 备用链接，需控制台开 VT100，
	// 否则二维码会退化成一片空白。
	enableVTProcessing()

	for attempt := 1; attempt <= tries; attempt++ {
		q, restore, err := quarkStartQRSession(exe, name)
		if err != nil {
			fmt.Printf("❌ 启动扫码会话失败: %v\n", err)
			os.Exit(1)
		}

		if attempt > 1 {
			fmt.Printf("\n⏰ 上一个二维码超时，已重新生成（第 %d/%d 次）\n", attempt, tries)
		}
		fmt.Print(q.Option.Help)
		if !strings.HasSuffix(q.Option.Help, "\n") {
			fmt.Println()
		}
		if u := qrURLRe.FindString(q.Option.Help); u != "" {
			fmt.Printf("二维码没显示出来时，用手机打开这个链接登录:\n  %s\n", u)
		}
		fmt.Println("用夸克 APP 扫描上面的二维码并在手机上确认（不用按回车），等待 cookie 写入……")

		// 回答 qr_poll（config_scan_complete=true）→ rclone 轮询夸克，
		// 扫码确认后写 cookie；超时约 3 分钟，输出直通（失败会带 rclone 用法提示）。
		err = runRclone(exe, "config", "create", name, "quark",
			"--non-interactive", "--continue", "--state", q.State, "--result", "true")
		if err == nil {
			return
		}
		restore() // 扫码失败/超时：把旧 cookie 写回，登录态不丢
		if attempt == tries {
			fmt.Printf("❌ 扫码失败（已重试 %d 次）: %v\n", tries, err)
			os.Exit(1)
		}
	}
}

// quarkStartQRSession 以 --non-interactive 启动扫码会话，返回问题 JSON 与**失败恢复函数**。
//
// ⚠️ 两坑（都实测过）：
//  1. `config create` 会**重建整个 remote 段** → 已有 cookie 被清掉；
//  2. `config show` 会把 cookie 掩码成 `*** ENCRYPTED ***` → 拿不到真值。
// 所以这里直接读写**原始 rclone.conf**：创建前快照 [name] 段，创建后/失败时
// 把丢掉的键（除 type/config_qr_session）原样写回：扫码成功 → 新 cookie 生效，
// 失败/超时 → 旧登录态不丢。
func quarkStartQRSession(exe, name string) (*qrQuestion, func(), error) {
	cfg := quarkRawConfigPath(exe)
	saved := quarkReadSectionRaw(cfg, name)
	restore := func() { quarkRestoreSectionRaw(cfg, name, saved) }

	c := exec.Command(exe, "config", "create", name, "quark", "--non-interactive")
	var stdout, stderr bytes.Buffer
	c.Stdout, c.Stderr = &stdout, &stderr
	if err := c.Run(); err != nil {
		restore() // 创建失败也可能已动过配置
		return nil, restore, fmt.Errorf("%v: %s", err, oneLine(stderr.String()))
	}
	quarkRestoreSectionRaw(cfg, name, saved) // 立刻补回丢失的键
	var q qrQuestion
	if err := json.Unmarshal(stdout.Bytes(), &q); err != nil {
		return nil, restore, fmt.Errorf("rclone 输出不是 JSON: %v（%s）", err, oneLine(stdout.String()))
	}
	if q.Error != "" {
		return nil, restore, errors.New(q.Error)
	}
	if q.State == "" {
		return nil, restore, fmt.Errorf("rclone 未返回扫码状态（%s）", oneLine(stdout.String()))
	}
	return &q, restore, nil
}

// quarkRawConfigPath 找到 rclone 的原始配置文件（不经过掩码）。
func quarkRawConfigPath(exe string) string {
	if out, err := rcloneOutput(exe, "config", "file"); err == nil {
		if p := strings.TrimSpace(out); p != "" && fileExists(p) {
			return p
		}
	}
	candidates := []string{}
	if d, err := os.UserConfigDir(); err == nil { // Windows: %AppData%
		candidates = append(candidates, filepath.Join(d, "rclone", "rclone.conf"))
	}
	if d := os.Getenv("APPDATA"); d != "" {
		candidates = append(candidates, filepath.Join(d, "rclone", "rclone.conf"))
	}
	for _, p := range candidates {
		if fileExists(p) {
			return p
		}
	}
	return ""
}

// quarkSectionName 找到段头行的索引（remote 名大小写不敏感，可带冒号）。
func quarkSectionName(line, name string) bool {
	line = strings.TrimSpace(line)
	if !strings.HasPrefix(line, "[") || !strings.HasSuffix(line, "]") {
		return false
	}
	sec := strings.ToLower(strings.TrimSuffix(strings.TrimSpace(line[1:len(line)-1]), ":"))
	return sec == strings.ToLower(strings.TrimSuffix(name, ":"))
}

// quarkReadSectionRaw 从原始 conf 读出 [name] 段的键值（**真值，不掩码**）。
func quarkReadSectionRaw(path, name string) map[string]string {
	if path == "" {
		return nil
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	out := map[string]string{}
	in := false
	for _, raw := range strings.Split(string(b), "\n") {
		line := strings.TrimRight(raw, "\r")
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, "#") || strings.HasPrefix(t, ";") {
			continue
		}
		if strings.HasPrefix(t, "[") && strings.HasSuffix(t, "]") {
			in = quarkSectionName(t, name)
			continue
		}
		if !in {
			continue
		}
		if i := strings.Index(t, "="); i > 0 {
			out[strings.TrimSpace(t[:i])] = strings.TrimSpace(t[i+1:])
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// quarkRestoreSectionRaw 把 saved 里存在、当前文件里丢失的键写回 [name] 段
//（type/config_qr_session 除外——那两个由 create 刚重建）。直接改文件：
// 绕开 config show 的掩码与 config update 的不确定性。
func quarkRestoreSectionRaw(path, name string, saved map[string]string) {
	if path == "" || len(saved) == 0 {
		return
	}
	b, err := os.ReadFile(path)
	if err != nil {
		log.Printf("⚠ 读配置文件失败: %v", err)
		return
	}
	lines := strings.Split(string(b), "\n")
	cur := map[string]string{}
	secStart, secEnd := -1, -1
	in := false
	for i, raw := range lines {
		t := strings.TrimSpace(strings.TrimRight(raw, "\r"))
		if strings.HasPrefix(t, "[") && strings.HasSuffix(t, "]") {
			if in {
				secEnd = i
				break
			}
			if quarkSectionName(t, name) {
				in, secStart = true, i
			}
			continue
		}
		if !in || t == "" || strings.HasPrefix(t, "#") || strings.HasPrefix(t, ";") {
			continue
		}
		if j := strings.Index(t, "="); j > 0 {
			cur[strings.TrimSpace(t[:j])] = strings.TrimSpace(t[j+1:])
		}
	}
	if secStart < 0 {
		log.Printf("⚠ 配置文件里找不到 [%s] 段，无法恢复参数", name)
		return
	}
	if secEnd < 0 {
		secEnd = len(lines)
	}

	insert := []string{}
	missing := []string{}
	for k, v := range saved {
		if k == "type" || k == "config_qr_session" {
			continue
		}
		if _, ok := cur[k]; ok {
			continue
		}
		insert = append(insert, k+" = "+v)
		missing = append(missing, k)
	}
	if len(insert) == 0 {
		return
	}
	// 插在段头之后
	lines = append(append(append([]string{}, lines[:secStart+1]...), insert...), lines[secStart+1:]...)
	out := strings.Join(lines, "\n")
	if err := os.WriteFile(path, []byte(out), 0o666); err != nil {
		log.Printf("⚠ 写回配置失败: %v", err)
		return
	}
	log.Printf("🔁 已保留原 remote 参数（%s）—— 扫码成功后新 cookie 会覆盖，失败则登录态不丢",
		strings.Join(missing, ", "))
}

// oneLine 把多行输出压成一行并截断，便于报错展示。
func oneLine(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	if len(s) > 300 {
		s = s[:300] + "…"
	}
	if s == "" {
		return "(空)"
	}
	return s
}

// runRclone 非交互执行 rclone 子命令（输出直通）。
func runRclone(exe string, sub ...string) error {
	c := exec.Command(exe, sub...)
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	return c.Run()
}

// runRcloneInteractive 交互执行（stdin 直通；QR/问答需要真 TTY，
// 必须在真实控制台运行本命令）。
func runRcloneInteractive(exe string, sub ...string) error {
	c := exec.Command(exe, sub...)
	c.Stdin = os.Stdin
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	return c.Run()
}

// rcloneOutput 非交互执行并捕获 stdout。
func rcloneOutput(exe string, sub ...string) (string, error) {
	c := exec.Command(exe, sub...)
	out, err := c.Output()
	return string(out), err
}

// runRcloneQuiet 静默执行并合并捕获 stdout/stderr（面板扫码用：
// 不往控制台刷 rclone 的用法提示，失败时由调用方展示）。
func runRcloneQuiet(exe string, sub ...string) (string, error) {
	c := exec.Command(exe, sub...)
	var buf bytes.Buffer
	c.Stdout, c.Stderr = &buf, &buf
	err := c.Run()
	return buf.String(), err
}

// quarkRemoteFlag 返回 run 命令使用的云端 fs。
// remote 为空 → 本地替身目录（P0/P1 测试路径）；否则为 rclone remote（如 quark:）。
func quarkRemoteFlag(remote string) string {
	return strings.TrimPrefix(remote, "/")
}
